<span href="#" class="gotop" onclick="topFunction()"><i class="fa fa-arrow-up"></i></span>
<!-- Footer -->
<footer>
    <h2>Copyright &copy; Beauty Queen, 2020 by <a href="https://www.kodak-development.com/" target="_blank">Kodak</a></h2>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="js/lightbox.js"></script>
<script async src="js/main.js"></script>
</body>
</html>