<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta property="og:image" content="img/bg.jpeg">
    <link rel="stylesheet" href="style/style.css">
    <link rel="icon" type="image/ico" href="img/logob.png" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" media="all and (device-width: 768px) and (device-height: 1024px) and (orientation:portrait)" href="style/ipad-portrait.css" />
    <link rel="stylesheet" media="all and (device-width: 1024px) and (device-height: 1366px) and (orientation:portrait)" href="style/ipad-pro.css" />
    <link rel="stylesheet" media="all and (device-width: 375px) and (device-height: 812px) and (orientation:portrait)" href="style/iphoneX.css" />
    <link rel="stylesheet" media="all and (device-width: 414px) and (device-height: 736px) and (orientation:portrait)" href="style/iphone678plus.css" />
    <link rel="stylesheet" media="all and (device-width: 320px) and (device-height: 568px) and (orientation:portrait)" href="style/iphone5.css" />
    <link rel="stylesheet" media="all and (device-width: 411px) and (device-height: 823px) and (orientation:portrait)" href="style/pixel2xl.css" />
    <link rel="stylesheet" media="all and (device-width: 411px) and (device-height: 731px) and (orientation:portrait)" href="style/pixel.css" />
    <link rel="stylesheet" type="text/css" href="style/lightbox.css">
    <!--[if IE]>
    <link rel="stylesheet" type="text/css" href="style/ie.css" />
    <![endif]-->
    <title>Beauty Queen | Salon lepote</title>
</head>
<body>
<div class="cta-btn">
    <a href="https://www.facebook.com/Beauty-Queen-1756570754646693/" target="_blank"><i class="fa fa-facebook-square"></i></a>
    <a href="https://www.instagram.com/beautyqueen.kg/" target="_blank"><i class="fa fa-instagram"></i></a>
    <button class="modalBtn"><i class="fa fa-phone-square"></i></button>
</div>
<!-- Header-->
<nav class="nav">
    <div class="logo">
        <a href="index"><img src="img/logo.png" alt="Beauty Queen studio lepote logo" class="logoImg"></a>
    </div>
    <ul class="nav-list">
        <li><a href="index#usluge" class="nav-links hover-link close-all">Usluge</a></li>
        <li><a href="index#alfaparf" class="nav-links hover-link close-all">Alfaparf</a></li>
        <li><a href="index#vacuslim48" class="nav-links hover-link close-all">Vacuslim 48</a></li>
        <li><a href="index#venčanje" class="nav-links hover-link close-all">Wedding paket</a></li>
        <li><a href="index#lokacija" class="nav-links hover-link close-all">Lokacija</a></li>
    </ul>
    <div class="burger">
        <div class="bar bar-1"></div>
        <div class="bar bar-2"></div>
        <div class="bar bar-3"></div>
    </div>
</nav> 
<!-- Modal-->
<div class="modal">
    <span class="modalClose">&times;</span>
    <div class="modal-header">
        <h1>Beauty Queen studio lepote</h1>
        <h2>Za vas tu i nakon radnog vremena !</h2>
    </div>
    <div class="modal-body">
        <h3>Radno vreme:</h3>
        <h4>pon.- pet. 10:00 - 20:00</h4>
        <h4>subota 10:00 - 20:00</h4>
        <h4>nedelja 10:00 - 17:00</h4>
    </div>
    <div class="modal-footer">
        <i class="fa fa-phone"></i>
        <a href="tel:+381 60 599 0009">+381 60 599 0009</a>
    </div>
</div>
